numbers = [10,1,4,5,46,89,78,77,44,2,5,9,1,45,44,33,10]
print(sorted(numbers))
print()
numbers.append(48)
print(numbers)
print()
numbers.pop()
print(numbers)
print()
numbers.insert(0,0)
print(numbers)
print()
del numbers[0]
print(numbers)
print()
print(len(numbers))
print()
print(sum(numbers))
print()
print(min(numbers))
print()
print(max(numbers))
print()
numbers.remove(5)
print(numbers)
print()
print(sum(numbers)/len(numbers))